version: '3.9'
services:
  ums:
    container_name: ums
    image: ums:v1
    ports:
      - 8888:8888
    depends_on:
      - mysql
    networks:
      - network
  mysql:
    container_name: db
    image: mysql:v1
    networks:
      - network
    environment:
      - MYSQL_ROOT_PASSWORD=wutianyu
networks:
  network: